import React, { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Eye, Package, Tag, X, CheckCircle2 } from 'lucide-react';
import { orderService } from '../../services/orderService';
import { Order, OrderPackage } from '../../types/order';
import { OrderDetailModal } from '../../components/orders/OrderDetailModal';

const packageType = (order: Order, pkg: OrderPackage) => pkg.package_type || (order.delivery_method === 'Packing Kayu' ? 'Packing Kayu' : 'Menunggu konfigurasi Admin');

export const SalesDashboard: React.FC = () => {
  const qc = useQueryClient(); const [detail, setDetail] = useState<Order | null>(null); const [photos, setPhotos] = useState<OrderPackage | null>(null); const [confirm, setConfirm] = useState<Order | null>(null); const [error, setError] = useState('');
  const ordersQuery = useQuery({ queryKey: ['sales-orders-lifecycle'], queryFn: () => orderService.getOrders({ per_page: 100 }), refetchInterval: 5000 });
  const progressQuery = useQuery({ queryKey: ['sales-packing-progress'], queryFn: () => orderService.getSalesPackingProgress({ per_page: 100 }), refetchInterval: 5000 });
  const informed = useMutation({ mutationFn: (id: number) => orderService.markSalesInformed(id), onSuccess: () => { setConfirm(null); qc.invalidateQueries({ queryKey: ['sales-orders-lifecycle'] }); qc.invalidateQueries({ queryKey: ['sales-packing-progress'] }); }, onError: (e: any) => setError(e?.response?.data?.message || 'Gagal menandai pesanan.') });
  const orders = ordersQuery.data?.data || []; const progress = progressQuery.data?.data || [];
  const waiting = orders.filter(o => o.status === 'WAITING_PACKING');
  const completed = progress.filter(o => (o.packages || []).some(p => p.photo_uploaded));
  const ready = progress.filter(o => (o.packages || []).some(p => p.tracking_number) && !o.sales_informed_at);
  const history = orders.filter(o => o.sales_informed_at);
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta' }).format(new Date());
  const todayCount = orders.filter(o => o.order_date === today).length;
  const allTracked = (o: Order) => !!o.packages?.length && o.packages.every(p => !!p.tracking_number);
  const plants = (o: Order) => o.items?.map(i => `${i.product_name} ×${i.quantity}`) || [];

  return <div className="space-y-4 max-w-5xl pb-24 font-sans text-slate-900">
    <header><h1 className="text-lg sm:text-xl font-bold">Sales Dashboard</h1><p className="text-xs text-slate-500 mt-0.5">Pantau pesanan, packing, foto, dan resi milik Anda.</p></header>
    <button onClick={() => window.location.assign(`/orders?order_date=${today}`)} className="w-full text-left bg-[#04593f] text-white rounded-2xl p-3.5"><span className="text-xs font-bold">Pesanan Dibuat Hari Ini · {todayCount} Order</span><span className="block text-[10px] text-emerald-100 mt-1">{today}</span></button>
    <section><h2 className="text-sm font-black mb-2">Menunggu Packing</h2><div className="grid gap-3 sm:grid-cols-2">{waiting.length === 0 ? <Empty text="Belum ada order menunggu packing." /> : waiting.map(o => <article key={o.id} className="bg-white border border-slate-200 rounded-2xl p-4 space-y-3"><div className="flex justify-between gap-2"><div><b className="text-xs">{o.order_number}</b><p className="font-bold text-sm mt-1">{o.customer_name}</p></div><span className="h-fit rounded-full bg-amber-50 border border-amber-200 px-2 py-1 text-[10px] font-bold text-amber-800">Menunggu Packing</span></div><div><p className="text-[10px] font-bold uppercase text-slate-400">Pesanan</p><ul className="mt-1 text-xs text-slate-600 space-y-0.5">{plants(o).map(p => <li key={p}>• {p}</li>)}</ul></div><div className="text-xs"><span className="font-bold text-slate-400">Jenis Paket: </span>{o.packages?.length ? o.packages.map(p => packageType(o, p)).join(' · ') : 'Menunggu konfigurasi Admin'}</div><button onClick={() => setDetail(o)} className="min-h-11 w-full rounded-xl bg-slate-100 text-slate-700 text-xs font-bold"><Eye className="inline w-4 h-4 mr-1" />Lihat Detail</button></article>)}</div></section>
    <section><h2 className="text-sm font-black mb-2">Packing Selesai</h2><div className="grid gap-3 sm:grid-cols-2">{completed.length === 0 ? <Empty text="Belum ada package dengan foto." /> : completed.map(o => <OrderPackageCard key={o.id} order={o} onPhoto={setPhotos} />)}</div></section>
    <section><h2 className="text-sm font-black mb-2 flex items-center gap-2"><Tag className="w-4 h-4 text-[#04593f]" />Daftar Pesanan Resi Terbit</h2><div className="space-y-3">{ready.length === 0 ? <Empty text="Belum ada resi package." /> : ready.map(o => <article key={o.id} className="bg-white border border-slate-200 rounded-2xl p-4 space-y-3"><div><b className="text-xs">{o.order_number}</b><p className="font-bold text-sm">{o.customer_name}</p></div><div className="space-y-2">{o.packages?.map(p => <div key={p.id} className="rounded-xl bg-slate-50 p-3 flex justify-between gap-2"><div><b className="text-xs">Paket {p.letter}</b><p className="text-xs text-slate-600">{p.tracking_number ? `✓ ${p.tracking_number}` : '○ Belum Resi'}</p></div>{p.photo_uploaded && <button onClick={() => setPhotos(p)} className="text-xs font-bold text-[#04593f]">Lihat Foto</button>}</div>)}</div><p className="text-xs font-bold text-slate-500">{o.packages?.filter(p => p.tracking_number).length || 0}/{o.packages?.length || 0} paket sudah ada resi</p><button disabled={!allTracked(o) || informed.isPending} onClick={() => setConfirm(o)} className="min-h-11 w-full rounded-xl bg-[#04593f] text-white text-xs font-black disabled:bg-slate-200 disabled:text-slate-400">{allTracked(o) ? '✓ Selesai Diinfokan' : '🔒 Selesai Diinfokan'}</button></article>)}</div></section>
    <section><h2 className="text-sm font-black mb-2">Riwayat Pesanan</h2><div className="space-y-2">{history.length === 0 ? <Empty text="Belum ada pesanan di riwayat." /> : history.map(o => <article key={o.id} className="bg-white border border-slate-200 rounded-2xl p-4"><b className="text-xs">{o.order_number}</b><p className="font-bold text-sm">{o.customer_name}</p><p className="text-xs text-emerald-700 font-bold mt-2">✓ Selesai Diinfokan</p><p className="text-[10px] text-slate-400">{o.sales_informed_at}</p></article>)}</div></section>
    <OrderDetailModal order={detail} onClose={() => setDetail(null)} />
    {photos && <PhotoModal pkg={photos} onClose={() => setPhotos(null)} />}
    {confirm && <div className="fixed inset-0 z-[9999] flex items-end sm:items-center justify-center bg-slate-900/40 p-3"><div className="w-full max-w-sm bg-white rounded-2xl p-5 space-y-4"><h2 className="font-black text-lg">Semua resi & foto sudah diinformasikan ke pembeli?</h2><p className="text-xs text-slate-600">✓ Nomor resi sudah tersedia<br/>✓ Foto paket sudah tersedia</p><p className="text-xs text-slate-500">Setelah dikonfirmasi, pesanan akan masuk ke Riwayat Pesanan.</p>{error && <p className="text-xs text-rose-600 font-bold">{error}</p>}<div className="grid grid-cols-2 gap-2"><button onClick={() => {setConfirm(null);setError('')}} className="min-h-11 rounded-xl bg-slate-100 font-bold">Batal</button><button onClick={() => informed.mutate(confirm.id)} disabled={informed.isPending} className="min-h-11 rounded-xl bg-[#04593f] text-white font-black disabled:opacity-50">{informed.isPending ? 'Menyimpan...' : 'Konfirmasi'}</button></div></div></div>}
  </div>;
};

const Empty: React.FC<{ text: string }> = ({ text }) => <div className="bg-white border border-slate-200 rounded-2xl p-5 text-xs text-slate-400">{text}</div>;
const OrderPackageCard: React.FC<{ order: Order; onPhoto: (pkg: OrderPackage) => void }> = ({ order, onPhoto }) => <article className="bg-white border border-slate-200 rounded-2xl p-4 space-y-3"><b className="text-xs">{order.order_number}</b><p className="font-bold text-sm">{order.customer_name}</p>{order.packages?.filter(p => p.photo_uploaded).map(p => <div key={p.id} className="rounded-xl bg-slate-50 p-3 flex items-center justify-between"><div><b className="text-xs">Paket {p.letter}</b><p className="text-xs text-slate-500">{packageType(order, p)}</p></div><button onClick={() => onPhoto(p)} className="min-h-11 rounded-xl bg-[#04593f] px-3 text-white text-xs font-bold">Lihat Foto Paket</button></div>)}</article>;
const PhotoModal: React.FC<{ pkg: OrderPackage; onClose: () => void }> = ({ pkg, onClose }) => <div className="fixed inset-0 z-[9999] bg-slate-900/60 flex items-end sm:items-center justify-center p-3"><div className="bg-white rounded-2xl w-full max-w-lg max-h-[90vh] overflow-y-auto p-4"><div className="flex justify-between items-center mb-3"><h2 className="font-black">Foto Paket {pkg.letter}</h2><button onClick={onClose} className="min-h-11 min-w-11 flex items-center justify-center"><X /></button></div><div className="grid gap-3">{pkg.packing_images?.map(img => <img key={img.id} src={img.image_url} alt={`Foto Paket ${pkg.letter}`} className="w-full rounded-xl object-contain max-h-[60vh]" />)}</div></div></div>;
