#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

if (file_exists($composerAutoload = __DIR__.'/vendor/autoload.php')) {
    require $composerAutoload;
}

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new \Symfony\Component\Console\Input\ArgvInput);

exit($status);
