-- ==========================================================
-- SQL SCRIPT UNTUK REFRESH MASTER TREES (59 VARIAN ADENIUM RESMI)
-- Salin seluruh teks ini dan Jalankan (Go/Kirim) di Tab SQL phpMyAdmin
-- ==========================================================

DELETE FROM `master_trees`;
ALTER TABLE `master_trees` AUTO_INCREMENT = 1;

INSERT INTO `master_trees` (`id`, `code`, `name`, `created_at`, `updated_at`) VALUES
(1, 'BA', 'BLACK AMARILYS', NOW(), NOW()),
(2, 'BBR', 'BANBURI', NOW(), NOW()),
(3, 'BD', 'BUTTERFLY DREAM', NOW(), NOW()),
(4, 'B.EV', 'BLACK EVIL', NOW(), NOW()),
(5, 'BF', 'BINH FENH', NOW(), NOW()),
(6, 'BH', 'BLACK HOLE', NOW(), NOW()),
(7, 'BLY', 'BLUE LILY', NOW(), NOW()),
(8, 'BM', 'BINH MINH', NOW(), NOW()),
(9, 'BNY', 'BANYEN', NOW(), NOW()),
(10, 'BT9', 'BAOTRAN 9', NOW(), NOW()),
(11, 'BL2', 'BLACK LOVER 2', NOW(), NOW()),
(12, 'CAN', 'CHOK AM NUAY', NOW(), NOW()),
(13, 'CHR', 'CHERRY', NOW(), NOW()),
(14, 'CJ', 'CRYSTAL JADE', NOW(), NOW()),
(15, 'CML', 'CAMELIA', NOW(), NOW()),
(16, 'COY', 'CHAMELION OF YELLOW', NOW(), NOW()),
(17, 'CV', 'CHILLY VERMILION', NOW(), NOW()),
(18, 'DH2', 'DUN HUANG 2', NOW(), NOW()),
(19, 'ETC', 'ENTRANCING', NOW(), NOW()),
(20, 'FL2', 'FIRST LOVE 2', NOW(), NOW()),
(21, 'GA', 'GOLDEN AGE', NOW(), NOW()),
(22, 'GD', 'GOLDEN DRAGON', NOW(), NOW()),
(23, 'GY', 'GOLDEN YEARS', NOW(), NOW()),
(24, 'HG', 'HOT GIRL', NOW(), NOW()),
(25, 'HK', 'HOA KAHN', NOW(), NOW()),
(26, 'HL', 'HONEY LEMON', NOW(), NOW()),
(27, 'HS', 'HANGSOON', NOW(), NOW()),
(28, 'JC', 'JULIUS CAESAR', NOW(), NOW()),
(29, 'JNT', 'JANTA', NOW(), NOW()),
(30, 'KALEI', 'KALEIDOSCOPE', NOW(), NOW()),
(31, 'LBT', 'LIBERTY', NOW(), NOW()),
(32, 'LF', 'LILAC FROST', NOW(), NOW()),
(33, 'LMT', 'LUMINTANG', NOW(), NOW()),
(34, 'LR', 'LOVE RAIN', NOW(), NOW()),
(35, 'LT', 'LONG TANH', NOW(), NOW()),
(36, 'LYLA', 'LYLA', NOW(), NOW()),
(37, 'MC', 'MONGCAM', NOW(), NOW()),
(38, 'M.PCS', 'MAGIC PRINCES', NOW(), NOW()),
(39, 'MQ', 'MENG QIAN', NOW(), NOW()),
(40, 'MS', 'MAGIC STAR', NOW(), NOW()),
(41, 'MSL', 'MUSSELA', NOW(), NOW()),
(42, 'PC2', 'PORCELINE 2', NOW(), NOW()),
(43, 'PL', 'PRETTY LADY', NOW(), NOW()),
(44, 'PLK', 'PURPLE LAKE', NOW(), NOW()),
(45, 'PMK', 'PHET MON KON', NOW(), NOW()),
(46, 'PP', 'PURPLE PUPIL', NOW(), NOW()),
(47, 'PRD', 'PARADISE', NOW(), NOW()),
(48, 'QY', 'QIAN YING', NOW(), NOW()),
(49, 'RNB', 'RAINBOW', NOW(), NOW()),
(50, 'SL', 'SWAN LAKE', NOW(), NOW()),
(51, 'SN', 'STARLESS NIGHT', NOW(), NOW()),
(52, 'SRW', 'SRIWIJAYA', NOW(), NOW()),
(53, 'SWL', 'SWALLOW', NOW(), NOW()),
(54, 'T.BELL', 'THE BELL', NOW(), NOW()),
(55, 'TRS', 'TAURUS', NOW(), NOW()),
(56, 'TT', 'TRUNG TINH', NOW(), NOW()),
(57, 'TW', 'TRIPLE WISH', NOW(), NOW()),
(58, 'WINE', 'WINE', NOW(), NOW()),
(59, 'YST', 'YELLOW STUN', NOW(), NOW());
