import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { managementService, Discount } from '../../services/managementService';

export const ManagementPage: React.FC<{ section: 'commission'|'discount' }> = ({ section }) => {
  const qc = useQueryClient(); const [editing, setEditing] = useState<number|null>(null); const [rate, setRate] = useState('');
  const [discount, setDiscount] = useState({ name:'', type:'percentage' as 'percentage'|'fixed', value:'', is_active:true });
  const commissions = useQuery({ queryKey:['owner-commissions'], queryFn: managementService.getCommissions, enabled: section==='commission' });
  const discounts = useQuery({ queryKey:['owner-discounts'], queryFn: managementService.getDiscounts, enabled: section==='discount' });
  const saveRate = useMutation({ mutationFn:({id,value}:{id:number,value:number})=>managementService.updateCommission(id,value), onSuccess:()=>{qc.invalidateQueries({queryKey:['owner-commissions']});setEditing(null);} });
  const saveDiscount = useMutation({ mutationFn:()=>managementService.createDiscount({...discount,value:Number(discount.value)}), onSuccess:()=>{qc.invalidateQueries({queryKey:['owner-discounts']});setDiscount({name:'',type:'percentage',value:'',is_active:true});} });
  const deactivate = useMutation({ mutationFn:(id:number)=>managementService.deactivateDiscount(id), onSuccess:()=>qc.invalidateQueries({queryKey:['owner-discounts']}) });
  return <div className="space-y-4 max-w-3xl"><h1 className="text-xl font-bold">Management · {section === 'commission' ? 'Commission' : 'Discount'}</h1>
    {section==='commission' ? <div className="space-y-2">{commissions.data?.data?.map(s=><div key={s.id} className="bg-white border rounded-2xl p-4 flex items-center justify-between"><div><b>{s.name}</b><p className="text-xs text-slate-500">{s.email} · Aktif</p></div>{editing===s.id?<div className="flex gap-2"><input className="w-20 border rounded-lg px-2" type="number" min="0" max="100" value={rate} onChange={e=>setRate(e.target.value)}/><button className="text-emerald-700 font-bold" onClick={()=>saveRate.mutate({id:s.id,value:Number(rate)})}>Simpan</button></div>:<button className="text-emerald-700 font-bold" onClick={()=>{setEditing(s.id);setRate(String(s.commission_rate));}}>Edit {s.commission_rate}%</button>}</div>)}</div> : <><form className="bg-white border rounded-2xl p-4 space-y-2" onSubmit={e=>{e.preventDefault();saveDiscount.mutate();}}><input required className="w-full border rounded-lg p-2" placeholder="Nama promo" value={discount.name} onChange={e=>setDiscount({...discount,name:e.target.value})}/><div className="flex gap-2"><select className="border rounded-lg p-2" value={discount.type} onChange={e=>setDiscount({...discount,type:e.target.value as 'percentage'|'fixed'})}><option value="percentage">Persentase</option><option value="fixed">Nominal</option></select><input required min="0" className="border rounded-lg p-2" type="number" placeholder="Nilai" value={discount.value} onChange={e=>setDiscount({...discount,value:e.target.value})}/><button className="bg-emerald-700 text-white rounded-lg px-4 font-bold">Tambah</button></div></form><div className="space-y-2">{discounts.data?.data?.map((d:Discount)=><div key={d.id} className="bg-white border rounded-2xl p-4 flex justify-between"><span><b>{d.name}</b><p className="text-xs text-slate-500">{d.type==='percentage'?`${d.value}%`:`Rp ${d.value.toLocaleString('id-ID')}`} · {d.is_active?'Aktif':'Nonaktif'}</p></span>{d.is_active&&<button className="text-rose-600 font-bold" onClick={()=>deactivate.mutate(d.id)}>Nonaktifkan</button>}</div>)}</div></>}
  </div>;
};
